/*COURSES SEQ*/
CREATE SEQUENCE SEQ_COU
  START WITH 1
  INCREMENT BY 1;

/*GRADES SEQ*/
CREATE SEQUENCE SEQ_GRA
  START WITH 1
  INCREMENT BY 1;

/*STUDENTS SEQ*/
CREATE SEQUENCE SEQ_STU
  START WITH 1
  INCREMENT BY 1;

/*TEACHERS SEQ*/
CREATE SEQUENCE SEQ_TEA
  START WITH 1
  INCREMENT BY 1;