/*TEACHERS INSERTION*/
BEGIN
  INSERT INTO TEACHERS VALUES(SEQ_TEA.currval,'Lavendelis','Researcher');
  INSERT INTO TEACHERS VALUES(SEQ_TEA.nextval,'Grundspenkis','Professor');
  INSERT INTO TEACHERS VALUES(SEQ_TEA.nextval,'Kirikova','Professor');
  INSERT INTO TEACHERS VALUES(SEQ_TEA.nextval,'Zagurskis','Professor');
  INSERT INTO TEACHERS VALUES(SEQ_TEA.nextval,'Grabis','Professor');
END;

/*CHECK INSERTION*/
SELECT * FROM DB_161ADM042.TEACHERS;

/*insert_courses.sql*/
BEGIN
INSERT INTO COURSES (C_ID, C_TITLE, C_TEACHER, C_C_POINTS)
VALUES (SEQ_COU.currval, 'Advanced Data Technologies',	1,4);
INSERT INTO COURSES (C_ID, C_TITLE, C_TEACHER, C_C_POINTS)
VALUES (SEQ_COU.NEXTVAL, 'Systems Theory',	2, 4);
INSERT INTO COURSES (C_ID, C_TITLE, C_TEACHER, C_C_POINTS)
VALUES (SEQ_COU.NEXTVAL, 'Knowledge Engineering',	3, 4);
INSERT INTO COURSES (C_ID, C_TITLE, C_TEACHER, C_C_POINTS)
VALUES (SEQ_COU.NEXTVAL, 'Grid Networking',	4, 2);
INSERT INTO COURSES (C_ID, C_TITLE, C_TEACHER, C_C_POINTS)
VALUES (SEQ_COU.NEXTVAL, 'AI in Business',	1, 4);
INSERT INTO COURSES (C_ID, C_TITLE, C_TEACHER, C_C_POINTS)
VALUES (SEQ_COU.NEXTVAL, 'Enterprise Architecture',	5, 2);
END;

/*insert_students.sql*/
BEGIN
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.currval, 'Janis',	'Koks',	'101RDB001',	1);
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.NEXTVAL, 'Peteris',	'Zars',	'071RDB111',	2);
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.NEXTVAL, 'Juris',	'Celms',	'061RDB121',	1);
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.NEXTVAL, 'Ivars',	'Lauks',	'051RDB131',	2);
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.NEXTVAL, 'Anna',	'Sakne',	'081RDB141',	3);
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.NEXTVAL, 'Ivo',	'Osis',	'071RDB151',	1);
  INSERT INTO STUDENTS (ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM, ST_GROUP)
  VALUES (SEQ_STU.NEXTVAL, 'Ilze',	'Ose',	'071RDB161',	2);
END;

/*insert_grades.sql*/
BEGIN
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.currval, 1, 1, 8, TO_DATE('28.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 1, 2, 4, TO_DATE('28.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 1, 6, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 2, 7, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 3, 9, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 4, 3, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 5, 10, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 6, 5, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 2, 7, 7, TO_DATE('23.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 1, 5, 6, TO_DATE('29.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 1, 6, 7, TO_DATE('29.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 1, 7, 9, TO_DATE('29.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 3, 1, 9, TO_DATE('11.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 3, 3, 9, TO_DATE('11.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 3, 4, 3, TO_DATE('11.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 3, 5, 4, TO_DATE('11.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 3, 6, 7, TO_DATE('11.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 3, 7, 10, TO_DATE('11.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 1, 7, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 2, 8, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 3, 7, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 4, 9, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 5, 2, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 6, 8, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 4, 7, 9, TO_DATE('07.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 1, 4, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 2, 8, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 3, 6, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 4, 8, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 5, 10, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 6, 10, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 5, 7, 10, TO_DATE('01.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 6, 1, 8, TO_DATE('03.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 6, 2, 8, TO_DATE('03.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 6, 3, 8, TO_DATE('03.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 6, 4, 8, TO_DATE('03.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 6, 5, 8, TO_DATE('03.06.10', 'DD.MM.YY' ));
INSERT INTO GRADES (G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE)
VALUES (SEQ_GRA.NEXTVAL, 6, 7, 9, TO_DATE('03.06.10', 'DD.MM.YY' ));
END;
