/*TEACHERS TABLE*/
CREATE TABLE TEACHERS
(
  T_ID NUMBER NOT NULL
, T_NAME VARCHAR2(20)
, T_TITLE VARCHAR2(20)
, CONSTRAINT TEACHERS_PK PRIMARY KEY
  (
    T_ID
  )
  ENABLE
);


/*COURSES TABLE*/
CREATE TABLE COURSES
(
  C_ID NUMBER NOT NULL ,
  C_TITLE VARCHAR2(40) ,
  C_TEACHER NUMBER NOT NULL ,
  C_C_POINTS NUMBER NOT NULL ,
  CHECK (C_C_POINTS > 0),
  CONSTRAINT COURSES_PK PRIMARY KEY
    (C_ID)
  ENABLE,
  CONSTRAINT COURSES_FK FOREIGN KEY
    (C_TEACHER)
    REFERENCES TEACHERS(T_ID)
);

/*STUDENTS TABLE*/
CREATE TABLE STUDENTS
(
  ST_ID NUMBER NOT NULL ,
  ST_NAME VARCHAR2(20) ,
  ST_SURNAME VARCHAR2(50) ,
  ST_ID_NUM VARCHAR2(10) ,
  ST_GROUP NUMBER NOT NULL ,
  CONSTRAINT STUDENTS_PK PRIMARY KEY
    (ST_ID)
  ENABLE
);

/*GRADES CREATION*/
CREATE TABLE GRADES
(
  G_ID NUMBER NOT NULL ,
  G_COURSE NUMBER NOT NULL ,
  G_STUDENT NUMBER NOT NULL ,
  G_GRADE NUMBER,
  G_DATE DATE,
  CONSTRAINT GRADES_PK PRIMARY KEY (G_ID) ENABLE ,
  CONSTRAINT GRADES_FK_C FOREIGN KEY
    (G_COURSE)
    REFERENCES COURSES(C_ID),
  CONSTRAINT GRADES_FK_S FOREIGN KEY
    (G_STUDENT)
    REFERENCES STUDENTS(ST_ID)
);
