/*BUILDINGS*/
CREATE SEQUENCE SEQ_BUI
  START WITH 1
  INCREMENT BY 1;

/*TREES*/
CREATE SEQUENCE SEQ_TRE
  START WITH 1
  INCREMENT BY 1;

/*ROADS*/
CREATE SEQUENCE SEQ_ROA
  START WITH 1
  INCREMENT BY 1;

/*POOL*/
CREATE SEQUENCE SEQ_PON
  START WITH 1
  INCREMENT BY 1;

/*POUND*/
CREATE SEQUENCE SEQ_POU
  START WITH 1
  INCREMENT BY 1;

/*SHOP*/
CREATE SEQUENCE SEQ_SHO
  START WITH 1
  INCREMENT BY 1;

/*FIELD*/
CREATE SEQUENCE SEQ_FIE
  START WITH 1
  INCREMENT BY 1;