/*
  MDSYS.SDO_DIM_ELEMENT has two dimensions:
    - X (min, max, accuracy)
    - Y(min, max, accuracy)
*/

begin
  INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
    VALUES ('FIELDS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );

  INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
    VALUES ('BUILDINGS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );

  insert into user_sdo_geom_metadata(table_name, column_name, diminfo, srid)
    values ('TREES', 'GEOMETRY', mdsys.sdo_dim_array(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );

  INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
    VALUES ('ROADS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );

  INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
    VALUES ('POOLS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );

  INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
    VALUES ('SHOPS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );

  INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
    VALUES ('PONDS', 'GEOMETRY', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 250, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 250, 1)), NULL
    );
end;