/*
  FK: Foreign key
  PK: Primary key
*/
CREATE TABLE BUILDING_FLOORS (
  BUILD_ID NUMBER NOT NULL CONSTRAINT FK_BUILD_FLOORS REFERENCES BUILDINGS (B_ID) ON DELETE CASCADE ,
  FLOOR_NUM NUMBER NOT NULL,
  CONSTRAINT PK_FLOORS PRIMARY KEY (BUILD_ID, FLOOR_NUM)
);

CREATE TABLE BUILDING_GARAGE (
  BUILD_ID NUMBER NOT NULL CONSTRAINT FK_BUILD_GARAGE REFERENCES BUILDINGS (B_ID) ON DELETE CASCADE ,
  GARAGE_FLOOR_NUM NUMBER NOT NULL ,
  CONSTRAINT PK_GARAGE PRIMARY KEY (BUILD_ID, GARAGE_FLOOR_NUM)
);

CREATE TABLE POOL_TYPE (
  POOL_ID NUMBER NOT NULL CONSTRAINT TY_ID REFERENCES POOLS (P_ID) ON DELETE CASCADE ,
  BUILDING_ID NUMBER NOT NULL CONSTRAINT PB_ID REFERENCES BUILDINGS(B_ID) ON DELETE CASCADE ,
  POOL_TYPE varchar(30) ,
  CONSTRAINT POOL_TYPE PRIMARY KEY (POOL_ID, BUILDING_ID)
);

CREATE TABLE TREE_AGE (
  TREE_ID NUMBER NOT NULL CONSTRAINT TR_ID REFERENCES TREES (T_ID) ON DELETE CASCADE ,
  TREE_AGE NUMBER NOT NULL,
  CONSTRAINT TREE_A PRIMARY KEY (TREE_ID, TREE_AGE)
);

CREATE TABLE ROAD_TYPE (
  ROAD_ID NUMBER NOT NULL CONSTRAINT ROADT_ID REFERENCES ROADS (R_ID) ON DELETE CASCADE ,
  ROAD_TYPE varchar(30) ,
  CONSTRAINT ROAD_T PRIMARY KEY (ROAD_ID, ROAD_TYPE)
);

CREATE TABLE SHOP_TYPE (
  SHOP_ID NUMBER NOT NULL CONSTRAINT SH_ID REFERENCES SHOPS (S_ID) ON DELETE CASCADE ,
  SHOP_TYPE VARCHAR(30) ,
  CONSTRAINT SHOP_T PRIMARY KEY (SHOP_ID, SHOP_TYPE)
);

CREATE TABLE POND_TYPE (
  POUND_ID NUMBER NOT NULL CONSTRAINT PO_ID REFERENCES PONDS (P_ID) ON DELETE CASCADE ,
  POUND_SURFACE NUMBER ,
  CONSTRAINT POUND_T PRIMARY KEY (POUND_ID, POUND_SURFACE)
);
