SELECT b_name, b_id FROM BUILDINGS b, ROADS r
WHERE b.b_name = 'garage' AND SDO_FILTER(b.GEOMETRY, r.GEOMETRY) = 'TRUE';


SELECT INDEX_NAME FROM USER_SDO_INDEX_INFO;
SELECT * FROM USER_SDO_GEOM_METADATA;



DROP INDEX FIELD_GEOM_IDX;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='FIELD';
