SELECT b_name, b_id FROM BUILDINGS b, ROADS r
WHERE b.b_name = 'garage' AND SDO_FILTER(b.GEOMETRY, r.GEOMETRY) = 'TRUE';


SELECT INDEX_NAME FROM USER_SDO_INDEX_INFO;
SELECT * FROM USER_SDO_GEOM_METADATA;



DROP INDEX FIELD_GEOM_IDX;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='FIELD';


/*queries find something using*/
/*using one layer*/
SELECT B.B_ID, B.B_NAME, COUNT(BI.FLOOR_NUM) AS "NUMBER OF FLOOR"
  FROM BUILDINGS B
  JOIN BUILDING_FLOORS BI ON B.B_ID = BI.BUILD_ID
  WHERE SDO_FILTER(B.GEOMETRY, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                                   MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
                                   MDSYS.SDO_ORDINATE_ARRAY(0,0,50,50)),
                     'QUERYTYPE=WINDOW') = 'TRUE'
  GROUP BY B.B_ID, B.B_NAME;
/*using two layers*/
SELECT B.B_ID, B.B_NAME
  FROM BUILDINGS B
  WHERE SDO_FILTER(B.GEOMETRY, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                                   MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
                                   MDSYS.SDO_ORDINATE_ARRAY(0,0,200,200)),
                     'QUERYTYPE=WINDOW') = 'TRUE'
UNION SELECT P.P_ID, P.P_NAME
  FROM POOLS P
  JOIN POOL_TYPE PI ON P.P_ID = PI.TYPE_ID
  WHERE SDO_FILTER(P.GEOMETRY, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                                   MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
                                   MDSYS.SDO_ORDINATE_ARRAY(0,0,200,200)),
                     'QUERYTYPE=WINDOW') = 'TRUE';

/*closest neighbour*/
SELECT B.B_ID, B.B_NAME, ROUND(MDSYS.SDO_NN_DISTANCE(1),1) DIST
 FROM BUILDINGS B
 WHERE SDO_NN(B.GEOMETRY,  MDSYS.SDO_GEOMETRY(2001, NULL,
    MDSYS.SDO_POINT_TYPE(10,10,NULL), NULL,  NULL),
    'SDO_NUM_RES=3', 1) = 'TRUE' ORDER BY DIST;
SELECT B.B_ID, B.B_NAME, ROUND(MDSYS.SDO_NN_DISTANCE(1),1) DIST
 FROM BUILDINGS B, PONDS P
 WHERE P.P_ID=9 AND SDO_NN(B.GEOMETRY,  P.GEOMETRY,
    'SDO_NUM_RES=3', 1) = 'TRUE' ORDER BY DIST;


/*which building has a pool*/
SELECT B.B_ID, B.B_NAME
 FROM BUILDINGS B, POOLS P
  JOIN POOL_TYPE PT ON P.P_ID = PT.POOL_ID
 WHERE PT.BUILDING_ID = B.B_ID;

/*within distance*/
SELECT B.b_name, P.P_NAME FROM BUILDINGS B, POOLS P
WHERE MDSYS.SDO_WITHIN_DISTANCE(B.GEOMETRY, P.GEOMETRY, 'distance = 10') = 'TRUE';

SELECT B.b_name, S.S_NAME FROM BUILDINGS B, SHOPS S
WHERE MDSYS.SDO_WITHIN_DISTANCE(B.GEOMETRY, S.GEOMETRY, 'distance = 25') = 'TRUE';

  /*get distance*/
  select B.b_name, P.P_NAME, sdo_geom.sdo_distance(P.geometry, B.geometry, 1) as distance
  from POOLS P, BUILDINGS B
  where mdsys.sdo_within_distance(B.geometry, P.geometry, 'distance=100') = 'TRUE';